import Head from "next/head";
import styles from "../styles/Home.module.css";

import { Typography } from "@mui/material";
import Image from "next/image";
import Layout from "../shared/components/Layout/layout";
import Logo from "../shared/images/logo.png";
export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image
          src={Logo}
          alt="Picture of the author"
          width={350}
          height={350}
        />
        <Typography style={{ color: "white", fontSize: 55, fontWeight: 700, marginTop: 50 }}>
          Community Project
        </Typography>
        <Typography
          style={{
            color: "#fdedda",
            fontSize: 20,
            fontWeight: 500,
            textAlign: "center",
          }}
        >
          Decentralized Treasury Protocol with <br />
          Reserve Currency
        </Typography>
      </main>
    </Layout>
  );
}
